---
- name: Restore the config with merge config
  # environment:
  #   ANSIBLE_LIBSSH_PUBLICKEY_ALGORITHMS: ssh-rsa
  cisco.ios.ios_config:
    src: "/tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt"
