- name: Restore selected backup
  ansible.builtin.debug:
    msg: "restoring from /backup/{{ rollback_date }}/{{ inventory_hostname }}.txt"

## overwrite doesn't work as of June 2025
- name: Include task list in play
  ansible.builtin.include_tasks: "ios/{{ restore_mode | default('overwrite') }}.yml"

- name: Print to terminal window
  ansible.builtin.debug:
    msg: "Restore is complete for device {{ inventory_hostname }} is set to {{ rollback_date }} timestamp, restored with restore_mode {{ restore_mode | default('overwrite') }} "
